name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚀
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Install pnpm 🚀
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies 🚀
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm update && pnpm install --no-frozen-lockfile

      - name: Setup Node.js 🚀
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build project 🚀
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          pnpm run build

      - name: Upload nakoruru 🚀
        uses: actions/upload-artifact@v3
        with:
          name: nakoruru
          path: dist
